export const Actiontypes = {
  FETCHPRODUCTS: "FETCH_PRODUCTS",
  ADDPRODUCTS: "ADD_PRODUCTS",
  SELECTPRODUCT : "SELECT_PRODUCT",
  REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
  FETCHCATEGORYDATA : "FETCH_CATEGORY_DATA",
  FILTERPRODUCTDATA : "FILTER_PRODUCT_DATA",
  ADDCARTITEM : "ADD_CARTITEM",
  DELETECARTITEM : "DELETE_CARTITEM"
}